version: '3'
services:
  db:
    build: .
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
    networks:
      - custom
    container_name: docker_postgreps
    ports:
      - '5432:5432'

networks:
  custom:
    external: true