version: '3'
services:
  redis:
    image: redis:alpine
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    container_name: redis
    ports:
    - '63679:6379'
    volumes:
    - /opt/vol/redis/redis.conf:/usr/local/etc/redis/redis.conf