apiVersion: v1
kind: Service
metadata:
  name: {{ template "hello-helm.fullname" . }}
  labels:
    app: {{ template "hello-helm.name" . }}
    chart: {{ template "hello-helm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port:  {{ .Values.service.port }}
    targetPort: 8000
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ template "hello-helm.name" . }}
    release: {{ .Release.Name }}