version: '3'
services:
  swagger-ui:
    image: robo2025/swagger-ui
    container_name: swagger-ui
    ports:
      - '8080:8080'
    volumes:
      - /opt/vol/swagger-ui/docs:/project/swagger-ui/public/docs