apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sso-api
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sso-api
    spec:
      containers:
      - name: sso-api
        image: robo2025/sso-api-l:dev-1.8.0
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: sso-api

---
apiVersion: v1
kind: Service
metadata:
  name: sso-api
  namespace: test
  labels:
    app: sso-api
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 8000
    nodePort: 30005
  selector:
    app: sso-api
