version: '3'

services:
  db:
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=liubiao123456
    ports:
      - '3307:3306'
    networks:
      - robo
    container_name: docker_mysql
    volumes:
      - ./db:/var/lib/mysql

networks:
  robo:
    external: true