version: '3'

services:
  mysql:
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=liubiao123456
    ports:
      - '3307:3306'
    networks:
      - custom
    container_name: docker_mysql
    volumes:
      - ./db:/var/lib/mysql

networks:
  custom:
    external: true