version: "2"

services: 
  zentao:
    image: idoop/zentao:latest
    container_name: zentao
    ports:
      - "9500:80"
      - "9501:3307"
    # if web response code: 310 ERR_TOO_MANY_REDIRECTS, please use host mode.
#    network_mode: "host"
    environment:
    # specifies you own account and password.
      USER: "root"
      PASSWD: "123456"
      BIND_ADDRESS: "false"
    volumes:
      - /opt/vol/zentao:/opt/zbox/
    restart: always
